#!/bin/bash

# Arguments from easy-hcx
nic=$1
save=$2
status=$3
channel=$4
deauth=$5

# Text coloring
yellow='\033[1;33m'
nc='\033[0m'

echo
echo -e "${yellow}This captures WPA handshakes and PMKIDs from all APs${nc}"

echo
echo -e "${yellow}Enter output name - a folder will be created in "$save" and a capture file inside with this name (.pcapng extension assumed): ${nc}"
read file

echo
echo -e "${yellow}Creating $save/$file${nc}"
mkdir -p $save/$file

echo
echo -e "${yellow}Running hcxdumptool -i $nic -o $save/$file/$file.pcapng --enable_status=$status -c $channel $deauth${nc}"
echo
echo -e "${yellow}Press Control-C when you've gotten enough.${nc}"
hcxdumptool -i $nic -o $save/$file/$file.pcapng --enable_status=$status -c $channel $deauth

read -p $'\e[91m'"Press enter to continue"$'\e[0m'
