#!/bin/bash

nic=$1
channel=$2

# Text coloring
yellow='\033[1;33m'
red='\033[1;91m'
nc='\033[0m'

echo
echo -e "${yellow}This will list available wifi networks. Copy the MAC address of the target AP and control-C when done${nc}"

echo
echo -e "${yellow}Running hcxdumptool -i $nic --do_rcascan -c $channel${nc}"

hcxdumptool -i $nic --do_rcascan -c $channel

